version: '3'

services:
  my_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["gunicorn", "--config", "gunicorn_config.py", "app:app"]
